name: Scala CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    - name: Package assembly
      run: sbt assembly
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: output-jar
        peth: target/scala-*/*-assembly-*.jar
